pipeline {
    agent any
    stages {
        stage('Performance Testing') {
            steps {
                echo 'Installing k6'
               sh 'sudo chmod +x setup_k6.sh'
                sh 'sudo k6_Perf_Test/setup_k6.sh'
                echo 'Running K6 performance tests...'
                sh 'k6 run loadtest/demok6.js'
            }
        }
    }
}
                                                                                                                                                                                                                            
